name: Macos RDP (Browser Login)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Enable RDP & Firewall Rules
        run: |
          sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.screensharing.plist
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -activate \
            -configure \
            -access -on \
            -privs -all \
            -restart -agent \
            -allowAccessFor -allUsers

          sudo /usr/libexec/ApplicationFirewall/socketfilterfw \
          --add /System/Library/CoreServices/RemoteManagement/ARDAgent.app
          sudo /usr/libexec/ApplicationFirewall/socketfilterfw \
          --unblockapp /System/Library/CoreServices/RemoteManagement/ARDAgent.app
          sudo defaults write /Library/Preferences/com.apple.RemoteManagement \
          ARD_AllowDirectLogins -bool true

      - name: Create RDP User
        run: |
          # Hardcoded to bypass generation errors but still pass Windows complexity rules
          $Password = "RootUser123!"
          net user RDP $Password /add
          net localgroup administrators RDP /add

      - name: Install Tailscale
        run: |
          curl -fsSL "https://pkgs.tailscale.com/stable/Tailscale-latest-macos.pkg" -o tailscale.pkg
          sudo installer -pkg tailscale.pkg -target /
          sleep 5

      - name: Start Tailscale & Connect
        run: |
         sudo /Applications/Tailscale.app/Contents/MacOS/Tailscale up \
         --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} \
         --hostname=cat-$GITHUB_RUN_ID

      - name: Keep Session Alive
        run: |
          echo "RDP Session is active."
          while ($true) { Start-Sleep -Seconds 300 }
